version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: orders
      - name: customers

  - name: stripe
    database: raw
    tables:
      - name: payments
        identifier: payment

        # Note: the following freshness test requires some daily volume of payments!
        loaded_at_field: "_batched_at::timestamp"
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

        columns:
          - name: id
            description: Unique ID of payment transaction
            tests:
              - unique
              - not_null

          - name: created
            description: Date of payment transaction
            tests:
              - not_null

          - name: orderid
            description: Associated order ID for which payment was processed
            tests:
              - not_null
              - relationships:
                  to: source('jaffel_store', 'orders')
                  field: id

          - name: status
            description: Payment status indicating a successful payment
            tests:
              - accepted_values:
                  values: ['fail', 'success']
          
          - name: paymentmethod
            description: Payment method used
            tests:
              - accepted_values:
                  values:
                    - credit_card
                    - coupon
                    - bank_transfer
                    - gift_card
          
          - name: amount
            description: Payment amount in USD * 100 (integer)
            tests:
              - not_null
              # - greater_than_zero -- TODO


models:
  - name: customers
    description: Customer list with basic order statistics
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: Date of first customer order; NULL when a customer has not yet placed an order.
      - name: most_recent_order_date
        description: Date of most recent customer order; NULL when a customer has not yet placed an order.
      - name: number_of_orders
        description: Total number of orders by customer. Can be 0.

      - name: total_lifetime_value_usd
        description: Successful payments for all orders from customers

  - name: stg_order_payments

  - name: stg_payments
    description: Payments staging table

    columns:
      - name: payment_id
        description: Unique ID
        
      - name: order_id
      - name: created_at
      - name: current_status


      - name: amount 

  - name: stg_customers
    description: This model cleans up customer data. Row-level object is the customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up order data. Row-level object is the order
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']